name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: Build source code
      run: |
        dotnet --info
        dotnet restore -p:Configuration=Release -p:Platform="Any CPU" -v normal ./src/
        dotnet build -p:Configuration=Release -p:Platform="Any CPU" -v normal ./src/

    - name: Test netstandard2.0 assembly in net80 application
      run: |
        dotnet test -f net8.0 ./src/Pkcs11Interop.X509Store.Tests/bin/Release/net80/Pkcs11Interop.X509Store.Tests.dll
